### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mariusGundersen** [emilol/RazorMailer#2] opened 2019-11-28 16:28 UTC
I get this error when it is trying `await razorPage.ExecuteAsync()` 

```
   at Microsoft.AspNetCore.Mvc.Razor.RazorPageBase.get_TagHelperFactory()
   at Microsoft.AspNetCore.Mvc.Razor.RazorPageBase.CreateTagHelper[TTagHelper]()
   at AspNetCore.Email_Index.<ExecuteAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyProject.RazorEngine.<GetOutput>d__3`1.MoveNext() 
```

I know this isn't much of a bug report, but this is pretty much all I have :p

It might be because I have dotnetcore 3.0 installed. Might something be different there?

**Comment by emilol** [comment] 2019-12-03 06:18
There's not a lot I can tell from the information you've pasted, and I'm not seeing the same error when I run up the tests from this solution - are you? Have you tried debugging the error you are getting to see if you can see what's causing it?

If you can show a bit more of your working - for example a minimal sample app where your error is reproducible then I can take a look for you. I'd definitely recommend posting your question on StackOverflow though, with your sample code. It's a much larger forum than this repo, which is just lil 'ole me 😅.

I'm going to close this issue, since it doesn't appear to be an issue with the repo itself. But please still feel free to reply with a link to a sample app with your error if you'd like some help with it. Or if you do think it's an issue with the repo feel free to provide some steps I can follow to reproduce it.

Your best bet though is to find others that have had the same problem on StackOverflow. Especially if you show as much as you can about how to reproduce your issue.

**Closed as completed by emilol** 2019-12-03 06:18 UTC

**Comment by kevin-david** [comment] 2020-01-08 13:49
@mariusGundersen I had this same issue with 3.0 and debugged .NET to find the cause: a missing `HttpContext`. I injected it into my derivative of the `RazorMailerRazorEngine` roughly [here](https://github.com/emilol/RazorMailer/blob/master/RazorMailer/Engine/RazorMailerRazorEngine.cs#L47), like:

```csharp
razorPage.ViewContext = new ViewContext
{
    Writer = output,
    HttpContext = m_httpContext
};
```

Since my first attempt at getting compiled views working was in a unit test, I used the `DefaultHttpContext` class which worked fine. I did have to hook up services like so:
```csharp
var server = new ComponentTestServerFixture();

var stubContext = new DefaultHttpContext
{
    RequestServices = server.Server.Host.Services
};

s_renderer = new RazorEmailRenderer(
    stubContext,
    new DiagnosticListener("UnitTests"));
```

That `ComponentTestServerFixture` is coming from the recommended [integration tests in ASP.NET core approach](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1), inspired by [this answer I found on SO](https://stackoverflow.com/a/53991944/4425370) and ended up with something like this:
```csharp
private class ComponentTestServerFixture :
    WebApplicationFactory<ComponentTestServerFixture.ComponentTestStartup>
{
    public ComponentTestServerFixture()
    {
        // Initialize the Server Host
        CreateDefaultClient();
    }

    public TService GetRequiredService<TService>() =>
        Server.Host.Services.GetRequiredService<TService>();

    protected override void ConfigureWebHost(IWebHostBuilder builder) =>
        builder.UseSolutionRelativeContentRoot("myFolder/Server.EmailTemplates");

    protected override IWebHostBuilder CreateWebHostBuilder()
    {
        var hostBuilder = new WebHostBuilder();
        return hostBuilder.UseStartup<ComponentTestStartup>();
    }

    internal class ComponentTestStartup : IStartup
    {
        public void Configure(IApplicationBuilder app) => app.UseMvc();

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            return services.BuildServiceProvider();
        }
    }
}
```


Unfortunately, I haven't been able to use compiled views because I can't get `_Layout.cshtml` to get used (maybe just missing functionality?), so I just end up with bare-bones output results :(

Hopefully, this helps you or someone else out!

**Comment by Mblkolo** [comment] 2020-07-29 10:35
@emilol add <body> tag for reproduce this error.

my Hello.cshtml
```
﻿<!DOCTYPE html>
<html>
    <body>
        Hello!
    </body>
</html>
```

from decompiled View_Hello.cs
```

    public virtual async Task ExecuteAsync()
    {
      ((RazorPageBase) this).BeginContext(0, 29, true);
      ((RazorPageBase) this).WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n    ");
      ((RazorPageBase) this).EndContext();
      ((RazorPageBase) this).BeginContext(29, 35, false);
      this.__tagHelperExecutionContext = this.__tagHelperScopeManager.Begin("body", (TagMode) 0, "1f2275f0fb6ef3a4f11db4644dd85bf0a510ddcc2713", (Func<Task>) (async () =>
      {
        ((RazorPageBase) this).BeginContext(35, 22, true);
        ((RazorPageBase) this).WriteLiteral("\r\n        Hello!\r\n    ");
        ((RazorPageBase) this).EndContext();
      }));
      this.__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = (BodyTagHelper) ((RazorPageBase) this).CreateTagHelper<BodyTagHelper>();
      this.__tagHelperExecutionContext.Add((ITagHelper) this.__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
      await this.__tagHelperRunner.RunAsync(this.__tagHelperExecutionContext);
      if (!this.__tagHelperExecutionContext.get_Output().get_IsContentModified())
        await this.__tagHelperExecutionContext.SetOutputContentAsync();
      ((RazorPageBase) this).Write((object) this.__tagHelperExecutionContext.get_Output());
      this.__tagHelperExecutionContext = this.__tagHelperScopeManager.End();
      ((RazorPageBase) this).EndContext();
      ((RazorPageBase) this).BeginContext(64, 11, true);
      ((RazorPageBase) this).WriteLiteral("\r\n</html>\r\n");
      ((RazorPageBase) this).EndContext();
    }
```

`CreateTagHelper<BodyTagHelper>()` - problem here

**Comment by Mblkolo** [comment] 2020-07-29 11:39
My solution

```
@removeTagHelper *, Microsoft.AspNetCore.Mvc.Razor.TagHelpers
@removeTagHelper *, Microsoft.AspNetCore.Mvc.Razor

<!DOCTYPE html>
<html>
<body>
    Hello!
</body>
</html>
```
removeTagHelper from https://stackoverflow.com/a/49501524
