### ISSUE TITLE
Can't cast object of type to type RazorPage

### ISSUE THREAD

**Issue by AndersMadsen** [emilol/RazorMailer#1] opened 2019-08-07 20:03 UTC
Hi Emily

I tried to follow your guide, when I do a render I get this error

System.AggregateException: 'One or more errors occurred. (Unable to cast object of type 'AspNetCore.EmailTemplates_Company_WelcomeMail' to type 'Microsoft.AspNetCore.Mvc.Razor.RazorPage`1[System.Object]'.)'

Any idea on how to fix this?

**Comment by emilol** [comment] 2019-08-08 05:30
Hi @AndersMadsen, glad to hear someone out there came across this and found it useful. To be honest you're the first person to reach out about this one, so good to hear the time spent to put it together and share has helped someone.

There's not a lot I can tell from the information you've pasted, and I'm not seeing the same error when I run up the tests from this solution - are you? Have you tried debugging the error you are getting to see if you what's causing it?

If you can show a bit more of your working - for example a minimal sample app where your error is reproducible then I can take a look for you. I'd definitely recommend posting your question on StackOverflow though, with your sample code. It's a much larger forum than this repo, which is just lil 'ole me 😅. 

I'm going to close this issue, since it doesn't appear to be an issue with the repo itself. But please still feel free to reply with a link to a sample app with your error if you'd like some help with it. Or if you do think it's an issue with the repo feel free to provide some steps I can follow to reproduce it.

Your best bet though to find others that have had the same problem is on StackOverflow, especially if you show as much as you can about how to reproduce your issue.

**Closed** 2019-08-08 05:31 UTC

**Comment by AndersMadsen** [comment] 2019-08-08 09:45
Ungh, it's part of a larger app I am making in asp.net core (no azure) and it's a 3 layered architecture, so it'll take a bit of time (which I unfortunately don't have) to write it out, I'll get around to it when I have a bit more time.

From what I can tell it finds the view since it find the object for it, but in the GetOutput method in RazorEngine (RazorMailerRazorEngine in your git project) it probably fails at 

` var razorPage = (RazorPage<TModel>)Activator.CreateInstance(compiledTemplate);`

as it's trying to cast the object to RazorPage but fails.

I don't really have as much knowledge in razor as you and I already commented out the bit that uses your template parser.
There is a third project which is just a simple console application that calls some functions in the BLL namespace.

https://pastebin.com/15289ZBy

I am using it along with the email service from 
https://dotnetcoretutorials.com/2017/11/02/using-mailkit-send-receive-email-asp-net-core/

And end up with code like this to use it and send an email

            ```
var message = EmailWorker.i.RenderView(EmailWorker.CompanyWelcomeMail,"testname");
            var to = new EmailAddress() { Name = "myName", Address = "test@mail.dk"};
            var from = new EmailAddress() { Name = "me", Address = "no-reply@mail.dk"};
            var subject = "welcome!!!";
            var email = new EmailMessage();
            email.ToAddresses.Add(to);
            email.FromAddresses.Add(from);
            email.Subject = subject;
            email.Content = message;
            EmailWorker.i.Send(email);
```

In my viewlibrary I have
EmailTemplates
|-Company
|----|----WelcomeMail.cshtml
|-Shared
|----|----_EmailLayout.cshtml
|_ViewImports.cshtml
|_ViewStart.cshtml

Thanks for the tutorial and the hard work by the way.

**Comment by emilol** [comment] 2019-08-08 12:24
hmm, does your razor view define a model? I have a suspicion it does and there's one isn't being passed in to you render call. If so you'll need to pass an instance of your model to the render method - there's a second overload for it on the template parser:

```
    public interface ITemplateParser
    {
        Task<string> RenderAsync(string name);
        Task<string> RenderAsync<TModel>(string name, TModel model);
    }
```

**Comment by emilol** [comment] 2019-08-08 12:25
hmm, does your razor view define a model? I have a suspicion it does and one isn't being passed in to you render call. If so you'll need to pass an instance of your model to the render method - there's a second overload for it on the template parser:

```
    public interface ITemplateParser
    {
        Task<string> RenderAsync(string name);
        Task<string> RenderAsync<TModel>(string name, TModel model);
    }
```

**Comment by AndersMadsen** [comment] 2019-08-09 09:29
Yep, you were right, I changed line 118 (see pastebin link) from

`        public string RenderView(string name,object model)`

To

`        public string RenderView<TModel>(string name, TModel model)`

It compiles now, however my layout file is not getting registered, I know it's not in the scope of what you did or needed, however would you know how to make it work with layout files?

**Comment by emilol** [comment] 2019-08-10 08:40
Oh awesome, glad I could help 👍 

I have no plans to add layout support - as you called out it was never needed for my use case. If you do end up adding support for layouts though, please do share!

**Comment by AndersMadsen** [comment] 2019-08-12 09:53
Thank you very much :)

Oh yes I recall, I would like to add support for it though, but I don't have a very in depth knowledge of Razor, can you point me in the right direction?
